---
name: PrivateMine
version: 1.0.0
main: PrivateMine\PVM
api: 4.12.8
author: AmitxD
website: https://github.com/Amitminer888/Private-Mine
commands:
 pvm:
  description: private mines
  usage: "/pvm <UI>"
  permission: privatemine.command.pvm
permissions:
  privatemine.command.pvm:
    description: "Allows the user to run the pvm command"
    default: true
...
